### ISSUE TITLE
Bunch of bugs.

### ISSUE THREAD

**Issue by CerberaSSB** [NyxTheShield/MIDI2FNF#1]
Don't know if I'm the only one with these issues but it doesn't work correctly for me. It gets stuck in the first section, it still randomizes the notes even if I put them down how you did when it shouldn't go random. If I look in debug mode most notes are out of the cubes but in the back of it in the black background. Don't know if I'm screwing something up. Been trying to fix it for an hour with no luck.

**Comment by NyxTheShield** [comment]
Can you provide the midi file that causes this?

**Comment by CerberaSSB** [comment]
[fresh.zip](https://github.com/NyxTheShield/MIDI2FNF/files/6185975/fresh.zip)
heres the midi pllus json result with fresh

**Comment by NyxTheShield** [comment]
Yup, mido (my midi parser) sucks and it was giving me wrong data, I will try to fix today!

**Comment by NyxTheShield** [comment]
> Thanks ^-^

Okay, I fixed a lot of bugs today, but your midi file wasn't a bug haha 

![image](https://user-images.githubusercontent.com/16619220/112089435-6c081880-8b70-11eb-87ab-cf1713264ada.png)

As you can see, both of your lanes are mapped to the midi channel 1. You need to map the upper lane to the midi channel 2 and you are good to go. (Like this one)
[fresh.zip](https://github.com/NyxTheShield/MIDI2FNF/files/6186747/fresh.zip)

**Comment by CerberaSSB** [comment]
[freshh.zip](https://github.com/NyxTheShield/MIDI2FNF/files/6186831/freshh.zip)
