### ISSUE TITLE
Ability to convert CH MIDIs to FNF?

### ISSUE THREAD

**Issue by ntvmb** [NyxTheShield/MIDI2FNF#15]
I've been wondering, is it possible to add the ability for this tool to convert MIDIs produced by [Moonscraper](https://github.com/FireFox2000000/Moonscraper-Chart-Editor) (charting tool for Clone Hero) to FNF? (with certain limitations, of course)

**Comment by ThM112** [comment]
I have attempted this actually but I'm getting an issue where the application says it's unable to run the script. But what you should try is to use moonscrapper to import a .chart file, then export it as a .mid file and see if that works out for you
