### ISSUE TITLE
File not coming out as ".json"

### ISSUE THREAD

**Issue by PotatoKing0419** [NyxTheShield/MIDI2FNF#23]
When I transalated the MIDI into a Song chart, it always appears as a "File" instead of a ".json". It doesn't seem to be a normal file though, as it opens with notepad. Inside the file looks like a normal .json, but every time I launch the song in Friday Night Funkin', it just crashes, and I presume this to be why.
![screenshot (2)](https://user-images.githubusercontent.com/92553022/137403721-6454c3c0-dba1-4d70-9b5e-918b63559180.PNG)

**Comment by CalypsoTH** [comment]
Just add .json to the file lol
